global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'backend'
    static_configs:
      - targets: ['host.docker.internal:8080']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s

  - job_name: 'celery_worker'
    static_configs:
      - targets: ['celery_worker_documents:8081']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s

